In [3]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [4]:
df = pd.read_csv('data.csv')
df.head()

age  gender type
0    1    male    a
1    2  female    b
2    3    male    b
3    4  female    b
4    5    male    a

In [18]:
pd.get_dummies(df)

age  gender_female  gender_male  type_a  type_b
0    1              0            1       1       0
1    2              1            0       0       1
2    3              0            1       0       1
3    4              1            0       0       1
4    5              0            1       1       0
5    6              1            0       1       0

In [35]:
train = df.iloc[0:4]
test = df.iloc[4:6]

In [61]:
train

age  gender type
0    1    male    a
1    2  female    b
2    3    male    b
3    4  female    b

In [62]:
test

age  gender type
4    5    male    a
5    6  female    a

In [75]:
np.array(['gender', 'type'])

array(['gender', 'type'], dtype='<U6')

In [76]:
encoder_object = OneHotEncoder(categories = np.array(['gender', 'type']))

In [77]:
encoder_object.fit_transform(df.values).toarray()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [69]:
encoder_object = encoder_object.fit(df.values)

In [78]:
encoder_object.get_feature_names()

NotFittedError: This OneHotEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [59]:
train_x = encoder_object.transform(train.values).toarray()
train_x

array([[1., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 1.]])

In [60]:
test_x = encoder_object.transform(test.values).toarray()
test_x

array([[0., 0., 0., 0., 1., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 1., 0.]])

In [72]:
encoder_object.fit_transform(df.values).toarray()

array([[1., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 1., 0.]])

In [74]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

data= [["AUS", "Sri"],["USA","Vignesh"],["IND", "Pechi"],["USA","Raj"]]

df = pd.DataFrame(data, columns=(['Country', 'Name']))
X = df.values

countries = np.unique(X[:,0])
names = np.unique(X[:,1])

countries

array(['AUS', 'IND', 'USA'], dtype=object)

In [ ]:
ohe = OneHotEncoder(categories=[countries]) # specify ONLY unique country names
tmp = ohe.fit_transform(X[:,0].reshape(-1, 1)).toarray()

X = np.append(tmp, names.reshape(-1,1), axis=1)

print (X)